In [6]:
import numpy as np

In [7]:
a = np.array([[1, 6],
            [2, 8],
            [3, 11],
            [3, 10], 
            [1, 7]])


In [9]:
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [13]:
mean_a = np.mean(a, axis = 0)
mean_a

array([2. , 8.4])

In [16]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [51]:
a_centered_sp = np.dot(a[0], a[1])
a_centered_sp

50

In [52]:
a_centered_sp = a_centered_sp / np.shape(a)[0]-1

In [53]:
a_centered_sp

9.0