In [1]:
import numpy as np

In [3]:
a = np.array([[1, 6],
            [2, 8],
            [3, 11],
            [3, 10], 
            [1, 7]])


In [4]:
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [5]:
mean_a = np.mean(a, axis = 0)
mean_a

array([2. , 8.4])

In [6]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [7]:
a_centered_sp = np.dot(a[0], a[1])
a_centered_sp

50

In [8]:
a_centered_sp = a_centered_sp / (np.shape(a)[0]-1)

In [9]:
a_centered_sp

12.5